// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfsSLTOGqTi5xVCGtMiKu47fzH3HPzyR8',
    appId: '1:551197401612:web:a5d4855664d8846fe50429',
    messagingSenderId: '551197401612',
    projectId: 'flutter-maps-ff568',
    authDomain: 'flutter-maps-ff568.firebaseapp.com',
    storageBucket: 'flutter-maps-ff568.firebasestorage.app',
    measurementId: 'G-F6124RLRWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZQMnPb1boBPZ3iQLqPHjvBxVLCo7gp30',
    appId: '1:551197401612:android:5f2e370bf3e8f902e50429',
    messagingSenderId: '551197401612',
    projectId: 'flutter-maps-ff568',
    storageBucket: 'flutter-maps-ff568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnKdXveg9FZ-x-E9epIxdy9VPyShLznbI',
    appId: '1:551197401612:ios:59ea327a6ebb93d9e50429',
    messagingSenderId: '551197401612',
    projectId: 'flutter-maps-ff568',
    storageBucket: 'flutter-maps-ff568.firebasestorage.app',
    iosBundleId: 'com.example.flutterMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnKdXveg9FZ-x-E9epIxdy9VPyShLznbI',
    appId: '1:551197401612:ios:59ea327a6ebb93d9e50429',
    messagingSenderId: '551197401612',
    projectId: 'flutter-maps-ff568',
    storageBucket: 'flutter-maps-ff568.firebasestorage.app',
    iosBundleId: 'com.example.flutterMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfsSLTOGqTi5xVCGtMiKu47fzH3HPzyR8',
    appId: '1:551197401612:web:07b437bea5efabb3e50429',
    messagingSenderId: '551197401612',
    projectId: 'flutter-maps-ff568',
    authDomain: 'flutter-maps-ff568.firebaseapp.com',
    storageBucket: 'flutter-maps-ff568.firebasestorage.app',
    measurementId: 'G-V355JB63LM',
  );

}